### PR TITLE
Issue #7: Memo bug

### LINKED ISSUE #7: Memo in Transactions is weird .
pizza was tasty
When I wrote "Pizza was tasty" it got converted something weird.

### PR DESCRIPTION
**Pull request by dospuntos**
This PR fixes a problem with escaped characters in transaction memos. Fixes #7 
I've also included an updated version of the CppSQLite3 library from https://github.com/neosmart/CppSQLite. The previous version caused some non-fatal warnings during the build process. I haven't seen any issues with this change.

In addition, some missing strings where added for translation, as mentioned in `ToDo_Spanish`. Maybe this program can be added to Polyglot at some point for additional translations? 

Note that the bug report message (`CapitalBe has run into a bug`)  is translatable, but not the actual bug report that will be saved and possibly sent to a developer.

### CODE REVIEW

**Comment by humdingerb** [comment]
As there is no working email address to send a report to, it may be best to remove that part.

What could be nice is to offer to create the bug report file and propose to upload it to CapitalBe's issue tracker. A button that'll open https://github.com/HaikuArchives/CapitalBe/issues would be nice, too, but only if clicking it wouldn't dismiss the alert...

**Comment by korli** [comment]
Build failed on x86_gcc2:
```
g++ -c src/Account.cpp  -Iobjects.x86-cc2-release/  -Isrc/ -I-  -I/boot/system/develop/headers/private/interface  -O3    -o "objects.x86-cc2-release/Account.o"
In file included from /home/runner/work/CapitalBe/CapitalBe/src/Database.h:9,
                 from /home/runner/work/CapitalBe/CapitalBe/src/Account.cpp:4:
/home/runner/work/CapitalBe/CapitalBe/src/CppSQLite3.h:42: parse error before `&&'
/home/runner/work/CapitalBe/CapitalBe/src/CppSQLite3.h:44: parse error before `&&'
/home/runner/work/CapitalBe/CapitalBe/src/CppSQLite3.h:44: `detail::SQLite3Memory::operator =(...)' must take exactly one argument
/home/runner/work/CapitalBe/CapitalBe/src/CppSQLite3.h:59: confused by earlier errors, bailing out
/boot/system/develop/etc/makefile-engine:300: recipe for target 'objects.x86-cc2-release/Account.o' failed
```

File: src/Locale.cpp [hunk 1]
```diff
@@ -802,13 +806,14 @@ void
...
+		B_TRANSLATE("CapitalBe has run into a bug. This shouldn't happen, but it has.\n"
 		"Would you like to:\n\n1) Have CapitalBe make an e-mail to send to Support\n"
 		"2) Save the bug to a text file for e-mailing later\n"
-		"3) Just quit and do nothing\n";
+		"3) Just quit and do nothing\n");
 
 	DAlert* alert =
-		new DAlert("Agh! Bug!", message.String(), "Make an E-mail", "Save to File", "Quit");
+		new DAlert(B_TRANSLATE("Agh! Bug!"), message.String(), B_TRANSLATE("Make an E-mail"),
+		B_TRANSLATE("Save to File"), B_TRANSLATE("Quit"));
```
Comment (humdingerb) [inline src/Locale.cpp:816]:
```suggestion
		B_TRANSLATE("Save bugreport"), B_TRANSLATE("Quit"));
```

**Comment by dospuntos** [comment]
I removed the option to report bugs by email, not sure if the wording is fine? This is what the bug alert looks like:

CapitalBe bugreport

Clicking "Save bugreport" will save a file to the desktop **and** open the browser to GitHub.

Still looking into the build fail on x86_gcc2

**Comment by dospuntos** [comment]
> Build failed on x86_gcc2:
> 

I've reverted to the previous version of CppSQLite3, the latest version seems to be using features not supported by GCC2. Debugging and refactoring this is goes a bit over my head...

**Comment by korli** [comment]
> > Build failed on x86_gcc2:
> 
> I've reverted to the previous version of CppSQLite3, the latest version seems to be using features not supported by GCC2. Debugging and refactoring this is goes a bit over my head...

We could switch to gcc 13 on x86. Maybe after this change?

**Comment by dospuntos** [comment]
@humdingerb - can this be merged now? There's a conflict with `en.catkeys`, after a previous merge, but I'm not sure how to solve that here on the PR, maybe the simplest way is to regenerate it after merging?

**Comment by humdingerb** [comment]
Unfortunatley, the PR cannot be merged until the conflicts are solved.
You need to switch to your PR branch, do a "git rebase master" and solve the conflicts that are pointed out. After you removed the conflicting parts, do a "git add locales/en.catkeys" and git rebase --continue".

**Comment by dospuntos** [comment]
OK, should be solved now, thank you for your patience and your instructions. More PR's coming soon (hopefully) with system colors etc.

File: src/Locale.cpp [hunk 2]
```diff
@@ -825,19 +830,16 @@ ShowBug(const char* string)
...
 		// Generate a text file of the bug on the Desktop
 		BString filename("/boot/home/Desktop/CapitalBe Bug Report ");
 		filename << real_time_clock() << ".txt";
 		BFile file(filename.String(), B_READ_WRITE | B_CREATE_FILE | B_ERASE_FILE);
 		file.Write(message.String(), message.Length());
 		file.Unset();
+
+		// Open GitHub in browser
+		char* argv[2] = {(char*)"https://github.com/HaikuArchives/CapitalBe/issues/", NULL};
+		be_roster->Launch("text/html", 1, argv);
```
Comment (korli) [inline src/Locale.cpp:842]: BURL("https://github.com/HaikuArchives/CapitalBe/issues/").OpenWithPreferredApplication() would be preferred.

Comment (humdingerb) [reply src/Locale.cpp]: @korli, is there another reason to do it like this, besides that's just what BURL was made for?
Just asking for other projects doing similar things...

**Comment by humdingerb** [comment]
@dospuntos, ready to put CapitalBe up at Polyglot or do you anticipate more immediate string related changes?

**Comment by dospuntos** [comment]
@humdingerb Please wait for for the next PR, there are some minor changes there.

**Comment by humdingerb** [comment]
Will do.

File: src/Locale.cpp (hunk 2 above)
Comment (korli) [reply src/Locale.cpp]: This is what 'open' uses,  and in fine use the correct mime type application/x-vnd.Be.URL.https

Comment (humdingerb) [reply src/Locale.cpp]: Thanks!
